rag_model_name: 'facebook/rag-token-nq'
dpr_ctx_encoder_model_name: 'facebook/dpr-ctx_encoder-multiset-base'
dpr_ctx_encoder_path: temp
embed: '1of1'
sharded_index: False
corpus: ''
output_dir: ''  # the output_dir will have the passages dataset and the hnsw_index.faiss
batch_size: 16
d: 768
m: 128
ef_search: 128
ef_construction: 200
index_batch_size: 100000
scalar_quantizer: -1
product_quantizer_m: -1  # suggested values of 8, 16, 32 - maybe we need much higher though
product_quantizer_sv_bits: 8  # probably don't change this
is_l2: False
num_vectors: -1
max_norm: -1
