train_file: data/totto2/triplets/train.jsonl
dev_file: data/totto2/triplets/dev.jsonl
output_dir: temp/tapas/verification/models/
lr: 5e-5
epochs: 5
train_batch_size: 4
eval_batch_size: 4
model_name_or_path: temp/tapas/verification/models/
train: False
eval: True
