train_file: temp/seed/sent_selection/totto_train.jsonl
dev_file: temp/seed/sent_selection/totto_dev.jsonl
output_dir: temp/tapex/sent_selection/models/
lr: 5e-5
train_batch_size: 8
eval_batch_size: 8
num_epochs: 5