defaults:
  - callbacks: defaults
  - logger: wandb
  - paths: defaults
  - trainer: gpu
train: True
evaluate: True
predict: True
model:
  _target_: read.dpr.module.ToTToModule
  model_name_or_path: t5-small
  num_labels: 2
  learning_rate: 2.0e-5
  adam_epsilon: 1.0e-8
  warmup_steps: 0
  weight_decay: 0.0
datamodule:
  _target_: read.dpr.datamodule.ToTToDataModule
  data_path: data/totto/train.jsonl
  tokenizer: t5-small
  train_batch_size: 64
  eval_batch_size: 64