defaults:
  - callbacks: defaults
  - logger: wandb
  - paths: defaults
  - trainer: gpu
train: True
dev: True
predict: True
model:
  _target_: read.dpr.module.DPRModule
  model_name_or_path: facebook/bart-large-mnli
  num_labels: 2
  learning_rate: 2.0e-5
  adam_epsilon: 1.0e-8
  warmup_steps: 0
  weight_decay: 0.0
  qry_encoder_name_or_path: facebook/dpr-question_encoder-multiset-base
  ctx_encoder_name_or_path: facebook/dpr-ctx_encoder-multiset-base
datamodule:
  _target_: read.dpr.datamodule.DPRDataModule
  dataset_name_or_path: temp/dpr_training_data/totto.jsonl
  positive_pid_file: data/totto/linearized/positive_pids/train.jsonl
  qry_tokenizer: facebook/dpr-question_encoder-multiset-base
  ctx_tokenizer: facebook/dpr-ctx_encoder-multiset-base
  batch_size: 192
  sample_negative_from_top_k: -1
  seq_len_c: 128
  seq_len_q: 64