train_file: temp/infotab/sent_selection/data/train.jsonl
dev_file: temp/infotab/sent_selection/data/dev.jsonl
test_file: temp/infotab/sent_selection/data/dev.jsonl
rand_perm: 1
single_sentence: 0
max_len: 512
tokenizer_type: roberta-large
model_name:  sent_model
output_dir: temp/infotab/sent_selection/models_new/
model_type: roberta-large
cache_dir: .cache/infotab/
batch_size: 1
epochs: 10
num_labels: 2
train_size: -1
cached: True
train: True
eval: True