train_file: temp/infotab/verification/train.jsonl
dev_file: temp/infotab/verification/dev.jsonl
test_file: temp/infotab/verification/dev.jsonl
rand_perm: 1
single_sentence: 0
max_len: 512
tokenizer_type: roberta-large
model_name: infotab_verification
output_dir: temp/infotab/verification/models
model_type: roberta-large
cache_dir: .cache/infotab/
batch_size: 4
epochs: 10
num_labels: 2
train_size: 20000
cached: True