input_file: data/totto2/augmented/dev.jsonl
batch_size: 16
searcher:
  type: hybrid
  faiss_index: pyserini_faiss_full
  lucene_index: temp/pyserini_index
  qry_encoder: temp/dpr_model/qry_encoder_dpr
  ctx_encoder: temp/dpr_model/ctx_encoder_dpr
sent_selection:
  model: temp/seed/sent_selection/model
verifier:
  model: models/22-09-04-02-43-32/facebook/bart-large-mnli_epoch=8-val_loss=0.02.ckpt
  tokenizer: facebook/bart-large