train: True
eval: True
scan: horizontal
data_dir: temp/tabfact/sent_selection
output_dir: temp/tabfact/sent_selection/models
fact: first
eval_batch_size: 8
balance: True
model_name_or_path: bert-base-multilingual-cased
task_name: QQP
period: 500
max_seq_length: 512
do_lower_case: True
train_batch_size: 6
learning_rate: 5e-5
num_train_epochs: 20
warmup_proportion: 0.1
seed: 42
gradient_accumulation_steps: 1