output: temp/eval/dpr_search_preds.jsonl
data: data/totto/linearized/positive_pids/dev.jsonl
qry_encoder_path: temp/dpr_model/qry_encoder_dpr
ctx_encoder_path: temp/dpr_model/ctx_encoder_dpr
faiss_index: pyserini_faiss_full
lucene_index: temp/pyserini_index
num_answers: 20  
batch_size: 20
num_processes: 10
include_passages: True 
ks:
  - 1
  - 5
  - 10