train_file: temp/infotab/sent_selection/totto_train.jsonl
dev_file: temp/infotab/sent_selection/totto_dev.jsonl
test_file: temp/infotab/sent_selection/totto_dev.jsonl
rand_perm: 1
single_sentence: 0
max_len: 512
tokenizer_type: roberta-large
model_name: infotab_sent_selection
output_dir: temp/infotab/sent_selection/models/
model_type: roberta-large
cache_dir: .cache/infotab/
batch_size: 4
epochs: 10
num_labels: 2
train_size: 20000
cached: True