input_file: data/totto2/augmented/dev.jsonl
output_file: temp/seed/baseline/dev.jsonl
batch_size: 32
devices: 0,1,2,3
searcher:
  type: hybrid
  faiss_index: pyserini_faiss_full
  lucene_index: temp/pyserini_index
  qry_encoder: temp/dpr/models/qry_encoder_dpr
  ctx_encoder: temp/dpr/models/ctx_encoder_dpr
sent_selection:
  model: temp/seed/sent_selection/models/model.ckpt
  tokenizer: facebook/bart-large
verifier:
  model: temp/seed/verification/models/model.ckpt
  tokenizer: facebook/bart-large-mnli